Script started on Wed 22 Nov 2017 01:03:26 AM PST
crystalcove% a[Kmake
gcc -ansi -std=c99 -Wall -c PhotoLab.c -o PhotoLab.o
gcc -ansi -std=c99 -Wall  PhotoLab.o FileIO.o Test.o Image.o -L. -lFilter -o PhotoLab
gcc -ansi -std=c99 -Wall -c -DDEBUG -c PhotoLab.c -o PhotoLab_DEBUG.o
gcc  PhotoLab_DEBUG.o FileIO.o Test.o Image.o -L. -lFilter -o PhotoLabTest
crystalcove% ./PhotoLab

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image vertically
10: Add border to an image
11: Add Noise to an image
12: Sharpen an image
13: Posterize an image
14: Add Motion Blur to an image
15: Crop an image
16: Resize an image
17: Adjust the Brightness and Contrast of an image
18: Add Watermark to an image
19: Test all functions
20: Exit
Please make your choice: 19
AutoTest finished successfully.
----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image vertically
10: Add border to an image
11: Add Noise to an image
12: Sharpen an image
13: Posterize an image
14: Add Motion Blur to an image
15: Crop an image
16: Resize an image
17: Adjust the Brightness and Contrast of an image
18: Add Watermark to an image
19: Test all functions
20: Exit
Please make your choice: 20
You exit the program.
crystalcove% valgrind --leak-check=full PhotoLabTest
==31628== Memcheck, a memory error detector
==31628== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==31628== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==31628== Command: PhotoLabTest
==31628== 
==31628== 
==31628== HEAP SUMMARY:
==31628==     in use at exit: 0 bytes in 0 blocks
==31628==   total heap usage: 127 allocs, 127 frees, 16,683,939 bytes allocated
==31628== 
==31628== All heap blocks were freed -- no leaks are possible
==31628== 
==31628== For counts of detected and suppressed errors, rerun with: -v
==31628== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 8 from 6)
crystalcove% clean
clean: Command not found.
crystalcove% make clean
rm -f *.o *.jpg PhotoLab PhotoLabTest bw.ppm negative.ppm colorfilter.ppm edge.ppm vflipflip.ppm shuffle.ppm vmirror.ppm border.ppm noise.ppm sharpen.ppm posterize.ppm blur.ppm libFilter.a libFileIO.a
crystalcove% exit
exit

Script done on Wed 22 Nov 2017 01:09:59 AM PST
