Script started on Thu 26 Oct 2017 02:10:48 PM PDT
zuma% exit./photolab[10Dgcc PhotoLab.c -ansi -std=c99 -Wall -o photolab
zuma% gcc PhotoLab.c -ansi -std=c99 -Wall -o photolab[47Dexit[K./photolab
--------------------------------
1: Load a PPM image
2: Save an image in PPM and JPEG format
3: Change a color image to Black & White
4: Make a negative of an image
5: Color filter an image
6: Sketch the edge of an image
7: Shuffle an image
8: Flip an image vertically
9: Mirror an image vertically
10: Add Border to an image
11: Test all functions
12: Exit
please make your choice: 11
Testing all of the functoins!
HSSOE.ppm was read.
Image converted to black and white!
bw.ppm was saved. 
bw.jpg was stored.
Black and White tested!

HSSOE.ppm was read.
Negative of Image was created!
negative.ppm was saved. 
negative.jpg was stored.
Negative tested!

HSSOE.ppm was read.
Color was filtered!
colorfilter.ppm was saved. 
colorfilter.jpg was stored.
Color Filter tested!

HSSOE.ppm was read.
edges detectededge.ppm was saved. 
edge.jpg was stored.
Edge tested!

HSSOE.ppm was read.
shuffle.ppm was saved. 
shuffle.jpg was stored.
shuffle tested!

HSSOE.ppm was read.
Image Flipped!
vflip.ppm was saved. 
vflip.jpg was stored.
Virtical Flip tested!

HSSOE.ppm was read.
image was vertically mirrored
vmirror.ppm was saved. 
vmirror.jpg was stored.
Virtical Mirror tested!

HSSOE.ppm was read.
Border addedborder.ppm was saved. 
border.jpg was stored.
Border tested!

--------------------------------
1: Load a PPM image
2: Save an image in PPM and JPEG format
3: Change a color image to Black & White
4: Make a negative of an image
5: Color filter an image
6: Sketch the edge of an image
7: Shuffle an image
8: Flip an image vertically
9: Mirror an image vertically
10: Add Border to an image
11: Test all functions
12: Exit
please make your choice: 12

BYE!

zuma% exit
exit

Script done on Thu 26 Oct 2017 02:11:00 PM PDT
